version: '2'
services:
    realfriends-app:
        image: realfriends
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://realfriends-postgresql:5432/realfriends
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    realfriends-postgresql:
        extends:
            file: postgresql.yml
            service: realfriends-postgresql
